version: '2.0'

networks:
  kong-net:
    driver: bridge

services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    restart: always
    networks:
    - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong1234
    ports:
    - "5432:5432"

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:2.1.2
    command: "kong migrations bootstrap"
    networks:
    - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_DB: kong
      KONG_PG_PASSWORD: kong1234
    links:
    - kong-database
    depends_on:
    - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:2.1.2
    restart: always
    networks:
    - kong-net
    environment:
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_DB: kong
      KONG_PG_PASSWORD: kong1234
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
    - kong-migration
    - kong-database
    ports:
    - "8001:8001"
    - "8000:8000"
    - "8443:8443"

  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:0.14.1
    command: "-c prepare -a postgres -u postgres://kong:kong1234@kong-database:5432/konga_db"
    networks:
    - kong-net
    restart: on-failure
    links:
    - kong-database
    depends_on:
    - kong-database

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:0.14.1
    restart: always
    networks:
    - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      DB_PASSWORD: kong1234
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      DB_DATABASE: konga_db
      NODE_ENV: production
    depends_on:
    - kong-database
    ports:
    - "1337:1337"
